name: Save FRP Binary

on:
  push:
    branches: [ main ]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Download frpc
        run: |
          wget https://github.com/fatedier/frp/releases/download/v0.61.1/frp_0.61.1_linux_amd64.tar.gz
          tar -xzf frp_0.61.1_linux_amd64.tar.gz
          cp frp_0.61.1_linux_amd64/frpc ./frpc

      - name: Upload frpc
        uses: actions/upload-artifact@v4
        with:
          name: frpc-binary
          path: frpc
          retention-days: 7
